general = {
    lock_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 300                                 # 5min
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
} # screen brighness

listener {
    timeout = 300                                 # 5min
    on-timeout = brightnessctl -sd *::kbd_backlight set 10
    on-resume = brightnessctl -rd *::kbd_backlight
} # keyboard brightness

listener {
    timeout = 420                                 # 7min
    on-timeout = pidof hyprlock || hyprlock 
} # lock screen when timeout has passed

listener {
    timeout = 480                                 # 8min
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
} # screen off after timeout

listener {
    timeout = 1200                                # 20min
    on-timeout = loginctl suspend                # suspend pc
} # suspend pc after 30min
