# exec = gsettings set org.gnome.desktop.interface gtk-theme 'wallbash-Gtk'
# exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    col.active_border = rgba(F0DAD2ff) rgba(523429ff) 45deg
    col.inactive_border = rgba(231F27ff) rgba(574355ff) 45deg
}

group {
    col.border_active = rgba(F0DAD2ff) rgba(523429ff) 45deg
    col.border_inactive = rgba(231F27cc) rgba(574355cc) 45deg
    col.border_locked_active = rgba(D9DBDAff) rgba(050505ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
